// supabase-svelte/src/lib/Account.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import type { AuthSession } from '@supabase/supabase-js';
    import { supabase } from '../supabaseClient';

    export let session = AuthSession;

    let loading = false;
    let username: string | null = null;
    let website: string | null = null;
    let avatarUrl: string | null = null;

    onMount(() => {
        getProfile()
    });

    const getProfile = async () => {
       try { 
            loading = true;
            const { user } = session;

            const { data, error, session } = await supabase
                .from('profiles')
                .select('username, website, avatar_url')
                .eq('id', user.id)
                .single();

            if (error && status !== 406) throw error;

            if (data) {
                username = data.username;
                website = data.website;
                avatarUrl = data.avatar_url;
            }
       } catch (error) {
            if (error instanceof Error) { 
                alert(error.message);
            }
       } finally {
            loading = false;
       }
    };


    const updateProfile = async () => {
       try { 
            loading = true;
            const { user } = session;

            const updates = {
                id: user.id,
                username, 
                website,
                avatarUrl: avatarUrl,
                updatedAt: new Date().toISOString(),
            }

            let error = await supabase.from('profiles').upsert(updates);

            if (error) throw error;
            
       } catch (error) {
            if (error instanceof Error) { 
                alert(error.message);
            }
       } finally {
            loading = false;
       }
    }

</script>

<form on:submit|preventDefault={updateProfile} class="form-widget">
  <div>Email: {session.user.email}</div>
  <div>
    <label for="username">Name</label>
    <input id="username" type="text" bind:value={username} />
  </div>
  <div>
    <label for="website">Website</label>
    <input id="website" type="text" bind:value={website} />
  </div>
  <div>
    <button type="submit" class="button primary block" disabled={loading}>
      {loading ? 'Saving ...' : 'Update profile'}
    </button>
  </div>
  <button type="button" class="button block" on:click={() => supabase.auth.signOut()}>
    Sign Out
  </button>
</form>

// user-management-app-1/src/Account.jsx
import { useState, useEffect } from 'react';
import { supabase } from './supabaseClient';

export default function Account({session}) {
    const [loading, setLoading] = useState(true);
    const [username, setUsername] = useState(null);
    const [website, setWebsite] = useState(null);
    const [avatar_url, setAvatarUrl] = useState(null);
    
    useEffect(() => {
        async function getProfile() {
            setLoading(true);
            const { user } = session;

            let { data, error } =  await supabase
                .from('profiles')
                .select(`username, website, avatar_url`)
                .eq('id', user.id)
                .single();

            if (error)
                console.warn(error);
            else if (data) {
                setUsername(data.username);
                setWebsite(data.website);
                setAvatarUrl(data.avatar_url)
            }

            setLoading(false);
        }
        
        getProfile();
    }, [session])

    async function updateProfile(event, avatarUrl) {
        event.preventDefault();

        setLoading(true);
        const { user } = session;

        const updates = {
            id: user.id,
            username,
            website,
            avatarUrl,
            updated_at: new Date(),
        }

        let { error } = await supabase.from('profiles').upsert(updates);

        if ( error ) {
            alert(error.message);
        } else {
            setAvatarUrl(avatarUrl);
        }

        setLoading(false);

    }

    return (
    <form onSubmit={updateProfile} className="form-widget">
      <div>
        <label htmlFor="email">Email</label>
        <input id="email" type="text" value={session.user.email} disabled />
      </div>
      <div>
        <label htmlFor="username">Name</label>
        <input
          id="username"
          type="text"
          required
          value={username || ''}
          onChange={(e) => setUsername(e.target.value)}
        />
      </div>
      <div>
        <label htmlFor="website">Website</label>
        <input
          id="website"
          type="url"
          value={website || ''}
          onChange={(e) => setWebsite(e.target.value)}
        />
      </div>

      <div>
        <button className="button block primary" type="submit" disabled={loading}>
          {loading ? 'Loading ...' : 'Update'}
        </button>
      </div>

      <div>
        <button className="button block" type="button" onClick={() => supabase.auth.signOut()}>
          Sign Out
        </button>
      </div>
    </form>
  )
}
