// user-management-app-1/src/App.jsx
import './App.css';
import { useState, useEffect } from 'react';
import { supabase } from './supabaseClient';
import Auth from './Auth';
import Account from './Account';

function App() {
    const [session, setSession] = useState(null);

    useEffect(() => {
        supabase.auth.getSession().then(({ data: { session }}) => {
            setSession(session);
        });
        supabase.auth.onAuthStateChange((_event, session) => {
            setSession(session);
        });
    }, []);

    return (
        <div className="container" style={{ padding: '50px 0 100px 0'}}>
            {!session ? <Auth /> : < Account key={session.user.id} session={session} /> }
        </div>
    )

}

export default App;

// supabase-svelte/src/App.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { supabase } from './supabaseClient';
    import type { AuthSession } from '@supabase/supabase-js';

    import Account from './lib/Account.svelte';
    import Auth from './lib/Auth.svelte';

    let session: AuthSession;

    onMount(() => {
        supabase.auth.getSession().then(({ data }) => { 
            session = data.session;
        });
        supabase.auth.onAuthStateChange((_event, _session) => { 
            session = _session;
        });
    });

</script>


<div class="container" style="padding: 50px 0 100px 0">
  {#if !session}
  <Auth />
  {:else}
  <Account {session} />
  {/if}
</div>
